#! /usr/bin/env zsh

# fix java applications
# https://wiki.archlinux.org/title/Java#Gray_window,_applications_not_resizing_with_WM,_menus_immediately_closing
export _JAVA_AWT_WM_NONREPARENTING=1

pgrep -x sxhkd > /dev/null || sxhkd &

# use polybar --list-monitors to get monitor tags
monitor_DP0=$(xrandr --query | grep 'DP-0')
if [[ $monitor_DP0 = *connected* ]]; then
    bspc monitor DP-2 -d I II III IV V VI
    bspc monitor DP-0 -d VII VIII IX
else
    bspc monitor -d I II III IV V VI VII VIII IX
fi


bspc config border_width         4
bspc config window_gap          10
bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#908caa"

bspc config split_ratio              0.5
bspc config borderless_monocle       true
bspc config gapless_monocle          true


bspc rule -a vlc state=floating center=true
bspc rule -a feh state=floating center=true
bspc rule -a gwenview state=floating center=true
bspc rule -a neovide state=floating center=true
bspc rule -a obs state=floating



# Fix cursor
xsetroot -cursor_name left_ptr &

# feh wallpaper
feh --bg-scale ~/Pictures/wallpaper/MountainFog.jpg
# feh --bg-scale --randomize ~/Pictures/wallpaper/*

# picom
picom -b --experimental-backends &

# dunst
dunst &

# fcitx5
fcitx5 &

# udiskie
udiskie &

# flameshot
flameshot &

# utools
utools &

# polybar
/home/last/.config/polybar/launch.sh
