#! /usr/bin/env zsh

pgrep -x sxhkd > /dev/null || sxhkd &

# use polybar --list-monitors to get monitor tags
monitor_DP0=$(xrandr --query | grep 'DP-0')
if [[ $monitor_DP0 != *disconnected* ]]; then
    bspc monitor DP-2 -d I II III IV V VI
    bspc monitor DP-0 -d VII VIII IX
else
    bspc monitor -d I II III IV V VI VII VIII IX
fi


# General config
bspc config border_width             3
bspc config window_gap               7

bspc config split_ratio              0.5
bspc config borderless_monocle       true
bspc config focus_follows_pointer    true
bspc config gapless_monocle          true
bspc config top_monocle_padding      5
bspc config bottom_monocle_padding   5
bspc config left_monocle_padding     5
bspc config right_monocle_padding    5

# Colors
# catppuccin platte
bspc config focused_border_color "#74c7ec" # sapphire
bspc config normal_border_color  "#6c7086" # overlay0

# Window Rules
bspc rule -a vlc                    state=floating center=true
bspc rule -a feh                    state=floating center=true
bspc rule -a Mumble                 state=floating
bspc rule -a obs                    state=floating
bspc rule -a Rofi                   manage=off
bspc rule -a '*:*:Fcitx Configuration' state=floating center=true


# Fix cursor
xsetroot -cursor_name left_ptr &

# Fix java application
# https://wiki.archlinux.org/title/Java#Gray_window,_applications_not_resizing_with_WM,_menus_immediately_closing
# set `_JAVA_AWT_WM_NONREPARENTING=1` see /etc/environment

# feh wallpaper
feh --bg-scale ~/Pictures/wallpaper/LofiGirl.png
# feh --bg-scale --randomize ~/Pictures/wallpaper/*

# picom
picom -b --experimental-backends &

# dunst
dunst &

# fcitx5
fcitx5 &

# udiskie
udiskie &

# polybar
/home/last/.config/polybar/launch.sh
