#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          10
bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#908caa"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a vlc state=floating center=true
bspc rule -a feh state=floating center=true
bspc rule -a gwenview state=floating center=true
bspc rule -a alacritty state=floating center=true
bspc rule -a neovide state=floating center=true
bspc rule -a obs state=floating
bspc rule -a uTools state=floating



# show cursor theme set by lxappearance(need package xorg-xsetroot)
xsetroot -cursor_name left_ptr &

# feh wallpaper
# feh --bg-scale ~/Pictures/wallpaper/Desktop.JPG
feh --bg-scale --randomize ~/Pictures/wallpaper/*

# picom
picom -b --experimental-backends &

# dunst
dunst &

# fcitx5
fcitx5 &

# udiskie
udiskie &

# flameshot
flameshot &

# utools
utools &

# polybar
/home/last/.config/polybar/launch.sh
