#!/bin/bash

DIR="$HOME/dotfile/dunst/icons"

function get_volume() {
    pactl get-sink-volume @DEFAULT_SINK@ | grep -o '[0-9]*%' | head -1 | sed 's#%##'
}

function is_mute() {
    # amixer -D pulse get Master | grep '%' | grep -oE '[^ ]+$' | grep off
    pactl get-sink-mute @DEFAULT_SINK@ | grep yes
}

function send_notification() {
    volume=$(get_volume)
    if [ "$volume" = "0" ]; then
        icon_name="$DIR/notification-audio-volume-muted.svg"
    else
        if [ "$volume" -lt "30" ]; then
            icon_name="$DIR/notification-audio-volume-low.svg"
        else
            if [ "$volume" -lt "80" ]; then
                icon_name="$DIR/notification-audio-volume-medium.svg"
            else
                icon_name="$DIR/notification-audio-volume-high.svg"
            fi
        fi
    fi
    # Send the notification
    dunstify "$volume%  " -i "$icon_name" -r 5555 -u low -h int:value:"$volume"
}

case $1 in
    up)
        # Unmute
        pactl set-sink-mute @DEFAULT_SINK@ no
        # +2%
        pactl set-sink-volume @DEFAULT_SINK@ +2%
        send_notification
        ;;
    down)
        # Unmute
        pactl set-sink-mute @DEFAULT_SINK@ no
        # -2%
        pactl set-sink-volume @DEFAULT_SINK@ -2%
        send_notification
        ;;
    mute)
        # Toggle mute
        pactl set-sink-mute @DEFAULT_SINK@ toggle
        if is_mute; then
            icon_name="$DIR/notification-audio-volume-muted.svg"
            dunstify "Muted  " -i "$icon_name" -r 5555 -u low -h string:synchronous:audio-volume
        else
            send_notification
        fi
        ;;
esac
